[verilog]
include_paths = [
  "hdl",
  "**",
  "testbench"
]

[vls]
max_nof_diagnostics = 10
cache_workspace_on_open = true
indent_size = 2
tabs_to_spaces = true
space_in_named_connection = false

[diagnostics]
undeclared_identifiers = true
unconnected_ports = true
missing_ports = true
missing_parameters = false
unassigned_parameters = true